[package]
name = "muzero"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bounded-vec-deque = "0.1.1"
ndarray = "0.15.6"
tch = "0.8.0"
rand = "0.8.5"
rayon = "1.5.3"